config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: [:index, :show], path: 'p'
  resources :cart_items

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:create, :update, :destroy]
  get 'profile', to: 'users#edit', as: 'profile'
  get 'register', to: 'users#new', as: 'register'

  post 'set_session_cart', to: 'cart_items#set_session_cart', as: 'session_cart'
  post 'set_session_address', to: 'cart_items#set_session_address', as: 'session_address'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user, foreign_key: 'session_id'
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  validates :name, :slug, presence: true, uniqueness: true

  # def to_param
  #   "#{slug}-#{id}"
  # end
  has_many :cart_items, dependent: :destroy
  has_many :product_colors, dependent: :destroy

  def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
end

app/models/shopping_session.rb
class ShoppingSession < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :cart_items, dependent: :destroy, foreign_key: 'session_id'
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :require_login

  def create
    product = Product.find(params[:slug])
    @cart_item = CartItem.where(product_id: product.id, session_id: session[:user_id]).last # active

    if @cart_item.present?
      new_quantity = @cart_item.quantity + params[:quantity].to_i
      @cart_item.update(quantity: new_quantity, price: product.price*new_quantity)
    else
      @cart_item = CartItem.create(product_id: product.id,
        quantity: params[:quantity], price: product.price * params[:quantity].to_i,
        session_id: session[:user_id])
    end
    # , size: params[:size], color: params[:color]
  end

  def index
    @cart_items = current_user.cart_items
    session[:booking] = nil
  end

  def set_session_cart
    session[:booking] = {cart_ids: params[:cart_ids]}
  end

  def set_session_address
    session[:booking].merge!({address: {fullname: params[:fullname],
      mobile_number: params[:mobile_number], city: params[:city],
      postcode: params[:postcode]}})

    respond_to do |format|
      format.json { render json: {fullname: params[:fullname]}}
    end
  end

  def destroy
    CartItem.find_by(id: params[:id], session_id: session[:user_id]).destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, only: :show

  def index
    @products = Product.page(params[:page]).per 9

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render :not_found # Xử lý khi không tìm thấy bản ghi
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'login', only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  # profile
  def edit; end

  def update
    @user.update_attributes user_params
    render :edit
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private
  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit :username, :password, :first_name, :last_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/_cart_item.html.erb
<div class="card ecommerce-card">
  <div class="item-img">
    <a href="app-ecommerce-details.html">
    <img src="<%= asset_path('1.png') %>" alt="img-placeholder" />
    </a>
  </div>
  <div class="card-body">
    <div class="item-name">
      <h6 class="mb-0"><a href="app-ecommerce-details.html" class="text-body"><%= cart_item&.product&.name %></a></h6>
      <span class="item-company">By <a href="javascript:void(0)" class="company-name">Apple</a></span>
      <div class="item-rating">
        <ul class="unstyled-list list-inline">
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="unfilled-star"></i></li>
        </ul>
      </div>
    </div>
    <span class="text-success mb-1">In Stock</span>
    <div class="cart-item-qty">
      <div class="input-group">
        <input class="touchspin-cart" type="number" value="<%= cart_item.quantity %>">
      </div>
    </div>

    <span class="delivery-date text-muted">Delivery by, Wed Apr 25</span>
    <span class="text-success">17% off 4 offers Available</span>
  </div>
  <div class="item-options text-center">
    <div class="item-wrapper">
      <div class="item-cost">
        <h4 class="item-price"><%= cart_item.product.price * cart_item.quantity %></h4>
        <p class="card-text shipping">
          <span class="badge badge-pill badge-light-success">Free Shipping</span>
        </p>
      </div>
    </div>
    <button type="button" class="btn btn-light mt-1 remove-wishlist" data-id="<%= cart_item.id %>">
      <i data-feather="x" class="align-middle mr-25"></i>
      <span>Remove</span>
    </button>
    <!-- <button type="button" class="btn btn-primary btn-cart move-cart">
      <i class="ficon" data-feather="shopping-cart"></i>
      <span class="text-truncate">MUA NGAY</span>
    </button> -->
  </div>
</div>

app/views/cart_items/_my_cart.html.erb
<ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
  <li class="dropdown-menu-header">
    <div class="dropdown-header d-flex">
      <h4 class="notification-title mb-0 mr-auto">My Cart</h4>
      <div class="badge badge-pill badge-light-primary"><%= @cart_items.length %> Items</div>
    </div>
  </li>
  <li class="scrollable-container media-list">
    <% @cart_items.each do |cart_item| %>
      <%= render "cart_items/my_cart_item", cart_item: cart_item %>
    <% end %>
  </li>
  <li class="dropdown-menu-footer">
    <div class="d-flex justify-content-between mb-1">
      <h6 class="font-weight-bolder mb-0">Total:</h6>
      <h6 class="text-primary font-weight-bolder mb-0">
        <%= @cart_items.sum(:price) %>
      </h6>
    </div>
    <a class="btn btn-primary btn-block" href="<%= cart_items_path %>">Cart item list</a>
  </li>
</ul>

app/views/cart_items/_my_cart_item.html.erb
<div class="media align-items-center">
  <img class="d-block rounded mr-1" src="../../../app-assets/images/pages/eCommerce/1.png" alt="donuts" width="62">
  <div class="media-body">
    <i class="ficon cart-item-remove" data-feather="x"></i>
    <div class="media-heading">
      <h6 class="cart-item-title"><a class="text-body" href="app-ecommerce-details.html"><%= cart_item.product.name %></a></h6>
      <small class="cart-item-by">By Apple</small>
    </div>
    <div class="cart-item-qty">
      <div class="input-group">
        <input class="touchspin-cart" type="number" value="<%= cart_item.quantity %>">
      </div>
    </div>
    <h5 class="cart-item-price"><%= cart_item.price %></h5>
  </div>
</div>