config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: [:index, :show], path: 'p'
  resources :cart_items

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:create, :update, :destroy]
  get 'profile', to: 'users#edit', as: 'profile'
  get 'register', to: 'users#new', as: 'register'

  post 'set_session_cart', to: 'cart_items#set_session_cart', as: 'session_cart'
  post 'set_session_address', to: 'cart_items#set_session_address', as: 'session_address'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :user, foreign_key: 'session_id'
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/discount.rb
class Discount < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/payment_detail.rb
class PaymentDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  validates :name, :slug, presence: true, uniqueness: true

  # def to_param
  #   "#{slug}-#{id}"
  # end
  has_many :cart_items, dependent: :destroy
  has_many :product_colors, dependent: :destroy

  def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
end

app/models/shopping_session.rb
class ShoppingSession < ApplicationRecord
end

app/models/size.rb
class Size < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :cart_items, dependent: :destroy, foreign_key: 'session_id'
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, only: :show

  def index
    @products = Product.page(params[:page]).per 9

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    begin
      @product = Product.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render :not_found # Xử lý khi không tìm thấy bản ghi
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "login"
  before_action :require_login, only: :destroy

  def new
    @user = User.new
  end

  def create
    user = User.find_by username: params[:user][:username]

    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully.'
    else
      flash.now[:alert] = 'Invalid username or password.'
      render :new
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end

  # private

  # def require_login
  #   unless @current_user
  #     redirect_to login_path, alert: 'You must be logged in to access this page.'
  #   end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'login', only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  # profile
  def edit; end

  def update
    @user.update_attributes user_params
    render :edit
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private
  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit :username, :password, :first_name, :last_name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_product.html.erb
<div class="card ecommerce-card">
  <div class="item-img text-center">
    <a href="app-ecommerce-details.html">
    <%= image_tag '1.png', class: "img-fluid card-img-top", alt: "img-placeholder" %>
    </a>
  </div>
  <div class="card-body">
    <div class="item-wrapper">
      <div class="item-rating">
        <ul class="unstyled-list list-inline">
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="filled-star"></i></li>
          <li class="ratings-list-item"><i data-feather="star" class="unfilled-star"></i></li>
        </ul>
      </div>
      <div>
        <h6 class="item-price"><%= product.price %></h6>
      </div>
    </div>
    <h6 class="item-name">
      <a class="text-body" href="app-ecommerce-details.html">
      <%= link_to product.name, product_path(id: product.to_param) %></a>
      <span class="card-text item-company">By <a href="javascript:void(0)" class="company-name">Apple</a></span>
    </h6>
    <p class="card-text item-description">
      <%= truncate(strip_tags(product.desc), length: 600) %>
    </p>
  </div>
  <div class="item-options text-center">
    <div class="item-wrapper">
      <div class="item-cost">
        <h4 class="item-price"><%= product.price %></h4>
      </div>
    </div>
    <!-- <a href="javascript:void(0)" class="btn btn-light btn-wishlist">
    <i data-feather="heart"></i>
    <span>Yeu thich</span>
    </a>
    <a href="javascript:void(0)" class="btn btn-primary btn-add-to-cart">
      <i data-feather="shopping-cart"></i>
      <span class="add-to-cart">Add to cart</span>
    </a> -->
    <!--  (Da ban het thi khong dc them) -->
  </div>
</div>

app/views/products/index.js.erb
$('.my-posts').append('<%= j render @products %>');
<% if @products.next_page %>
  $('.pagination').replaceWith('<%= j paginate @products %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/users/new.html.erb
<div class="app-content content ">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
            <div class="auth-wrapper auth-v2">
                <div class="auth-inner row m-0">
                    <!-- Brand logo--><a class="brand-logo" href="javascript:void(0);">
                        <svg viewBox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="28">
                            <defs>
                                <lineargradient id="linearGradient-1" x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%">
                                    <stop stop-color="#000000" offset="0%"></stop>
                                    <stop stop-color="#FFFFFF" offset="100%"></stop>
                                </lineargradient>
                                <lineargradient id="linearGradient-2" x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%">
                                    <stop stop-color="#EEEEEE" stop-opacity="0" offset="0%"></stop>
                                    <stop stop-color="#FFFFFF" offset="100%"></stop>
                                </lineargradient>
                            </defs>
                            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <g id="Artboard" transform="translate(-400.000000, -178.000000)">
                                    <g id="Group" transform="translate(400.000000, 178.000000)">
                                        <path class="text-primary" id="Path" d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill: currentColor"></path>
                                        <path id="Path1" d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="url(#linearGradient-1)" opacity="0.2"></path>
                                        <polygon id="Path-2" fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"></polygon>
                                        <polygon id="Path-21" fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"></polygon>
                                        <polygon id="Path-3" fill="url(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"></polygon>
                                    </g>
                                </g>
                            </g>
                        </svg>
                        <h2 class="brand-text text-primary ml-1">Vuexy</h2>
                    </a>
                    <!-- /Brand logo-->
                    <!-- Left Text-->
                    <div class="d-none d-lg-flex col-lg-8 align-items-center p-5">
                        <div class="w-100 d-lg-flex align-items-center justify-content-center px-5">
                          <img class="img-fluid" src="<%= asset_path('register-v2.svg') %>" alt="Register V2" /></div>
                    </div>
                    <!-- /Left Text-->
                    <!-- Register-->
                    <div class="d-flex col-lg-4 align-items-center auth-bg px-2 p-lg-5">
                        <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">
                            <h2 class="card-title font-weight-bold mb-1">Adventure starts here 🚀</h2>
                            <p class="card-text mb-2">Make your app management easy and fun!</p>
                            <%= form_with model: @user, url: users_path, method: "POST", class: "auth-register-form mt-2" do |f| %>
                              <%= @csrf %>
                              <div class="form-group">
                                  <label class="form-label" for="register-username">Username</label>
                                  <input class="form-control" id="register-username" type="text" name="user[username]" placeholder="johndoe" aria-describedby="register-username" autofocus="" tabindex="1" />
                              </div>
                              <div class="form-group">
                                  <label class="form-label" for="register-lastname">Last name</label>
                                  <input class="form-control" id="register-lastname" type="text" name="user[last_name]" placeholder="john" aria-describedby="register-email" tabindex="2" />
                              </div>
                              <div class="form-group">
                                  <label class="form-label" for="register-password">Password</label>
                                  <div class="input-group input-group-merge form-password-toggle">
                                      <input class="form-control form-control-merge" id="register-password" type="password" name="user[password]" placeholder="············" aria-describedby="register-password" tabindex="3" />
                                      <div class="input-group-append"><span class="input-group-text cursor-pointer"><i data-feather="eye"></i></span></div>
                                  </div>
                              </div>
                              <div class="form-group">
                                  <div class="custom-control custom-checkbox">
                                      <input class="custom-control-input" id="register-privacy-policy" type="checkbox" tabindex="4" />
                                      <label class="custom-control-label" for="register-privacy-policy">I agree to<a href="javascript:void(0);">&nbsp;privacy policy & terms</a></label>
                                  </div>
                              </div>
                              <%= f.submit "Sign up", class: "btn btn-primary btn-block", tabindex: "5" %>
                            <% end %>
                            <p class="text-center mt-2"><span>Already have an account?</span><a href="page-auth-login-v2.html"><span>&nbsp;Sign in instead</span></a></p>
                            <div class="divider my-2">
                                <div class="divider-text">or</div>
                            </div>
                            <div class="auth-footer-btn d-flex justify-content-center"><a class="btn btn-facebook" href="javascript:void(0)"><i data-feather="facebook"></i></a><a class="btn btn-twitter white" href="javascript:void(0)"><i data-feather="twitter"></i></a><a class="btn btn-google" href="javascript:void(0)"><i data-feather="mail"></i></a><a class="btn btn-github" href="javascript:void(0)"><i data-feather="github"></i></a></div>
                        </div>
                    </div>
                    <!-- /Register-->
                </div>
            </div>
        </div>
    </div>
</div>